services:
  shorten_url:
    container_name: shorten-url
    build:
      context: .
      dockerfile: Dockerfile
    image: minhleduc0210/shorten-url:latest  # Keep it if you want to push to Docker Hub
    tty: true
    stdin_open: true
    env_file:
      - .env
    command: fastapi run app --host 0.0.0.0 --port 1802
    ports:
      - "1802:1802"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1802/api/v1/info"]
      interval: 5s
      timeout: 5s
      retries: 3