services:
  shorten-url:
    stdin_open: true
    tty: true
    container_name: shorten-url
    image: minhleduc0210/shorten-url:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7717:7771

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_volume:/data/db
      
volumes:
  mongodb_data_volume:
    external: true
