services:
  shorten-url:
    image: minh.leduc.0210/shorten-url:latest
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 7717:7771

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27027:27017
    volumes:
      - mongodb_data_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: minhleduc
      MONGO_INITDB_ROOT_PASSWORD: 7777
      
volumes:
  mongodb_data_volume:
    external: true