version: '3.3'
services:
  minio:
    tty: true
    stdin_open: true
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data_volume:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  minio_data_volume:
    external: true
