services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sY8egQUZ7IRhhTm
      
volumes:
  mongodb_data_volume:
    external: true